### PR TITLE
create switch audio for switchaudio-osx

### PR DESCRIPTION
**Pull request by liCells**
Create `switch audio` to adapt to Ventura, implemented using `switchaudio-osx`.

### CODE REVIEW

**Comment by alanhg** [comment]
The current best method is still AppleScript, isn't it? The main problem is that switchaudio-osx does not support Airplay devices. What do you think?

**Comment by liCells** [comment]
Yes, initially I also considered using AppleScript for the task. However, I found that `switchaudio-osx` is more convenient and concise for the implementation.

As for Airplay related functionalities.....
I'm not familiar with them, as I only have a MacBook as my Apple device.🫣🫣

**Comment by liCells** [comment]
I have changed my approach to retrieve the relevant devices.

```zsh
echo '<?xml version="1.0"?><items>'

system_profiler SPAudioDataType -json | jq -r '.SPAudioDataType[]._items[] | select(has("coreaudio_device_output"))._name' | while read line; do
    echo "<item arg=\"$line\"><title>$line</title></item>"
done

echo '</items>'
```

Can you help me test two questions?

1. Can Airplay devices be retrieved?
2. Can switchaudio-osx switch to Airplay devices?

**Comment by alanhg** [comment]
翻了下你的profile，我可以切中文了。这个我一会儿看下。
关键是这个命令行工具并不支持AirPlay。这个是确定是现状局限性，我主要不会objectc。

**Comment by liCells** [comment]
英语的确有些烂，还得找AI润色。
我也不会object-c，不过我的需求比较简单，就是切换输出设备就行😂。

我理解这个system_profiler获取到的数据应该是和System Information.app一样的，如果在系统信息中有对应的设备，那这个命令应该也能获取到。

**Comment by alanhg** [comment]
> I have changed my approach to retrieve the relevant devices.
> 
> ```shell
> echo '<?xml version="1.0"?><items>'
> 
> system_profiler SPAudioDataType -json | jq -r '.SPAudioDataType[]._items[] | select(has("coreaudio_device_output"))._name' | while read line; do
>     echo "<item arg=\"$line\"><title>$line</title></item>"
> done
> 
> echo '</items>'
> ```
> 
> Can you help me test two questions?
> 
> 1. Can Airplay devices be retrieved?
> 2. Can switchaudio-osx switch to Airplay devices?

1. 不可以获取到AirPlay设备
2. 还是之前的结论switchaudio-osx  not support airplay.

**Pull request closed without merging**
